AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Ansible Course - Managed Nodes Common Resources
  IAM Role, Instance Profile, Security Group

Resources:
  ManagedNodeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ansible-managed-node-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  ManagedNodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: ansible-managed-node-profile
      Roles:
        - !Ref ManagedNodeRole

  ManagedNodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Ansible Managed Nodes
      GroupName: ansible-managed-node-sg
      VpcId: !ImportValue ansible-course-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !ImportValue ansible-course-sg-id
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: ansible-managed-node-sg

Outputs:
  InstanceProfileName:
    Description: Instance Profile Name for Managed Nodes
    Value: !Ref ManagedNodeInstanceProfile
    Export:
      Name: ansible-managed-profile

  SecurityGroupId:
    Description: Security Group ID for Managed Nodes
    Value: !Ref ManagedNodeSecurityGroup
    Export:
      Name: ansible-managed-sg-id
