---
# tasks/main.yaml - Webserver role 主任务

- name: Install web server package
  ansible.builtin.dnf:
    name: "{{ webserver_package }}"
    state: present
  tags:
    - webserver
    - install

- name: Create document root
  ansible.builtin.file:
    path: "{{ webserver_document_root }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags:
    - webserver
    - configure

- name: Deploy httpd.conf
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    mode: '0644'
    backup: true
    validate: httpd -t -f %s
  notify: Restart httpd
  tags:
    - webserver
    - configure

- name: Deploy default index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ webserver_document_root }}/index.html"
    mode: '0644'
  when: webserver_deploy_default_page
  tags:
    - webserver
    - deploy

- name: Configure firewall for HTTP
  ansible.posix.firewalld:
    port: "{{ webserver_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  when: webserver_firewall_enabled
  ignore_errors: true
  tags:
    - webserver
    - firewall

- name: Ensure httpd is started and enabled
  ansible.builtin.service:
    name: "{{ webserver_service }}"
    state: started
    enabled: true
  tags:
    - webserver
    - service
