all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      hosts:
        al2023-1.ans.local:
      vars:
        http_port: 80
    dbservers:
      hosts:
        al2023-2.ans.local:
      vars:
        db_port: 3306
    production:
      children:
        webservers:
        dbservers:
